### ISSUE TITLE
React-Globalize + FormatCurrency + Globalize-Compiler

### ISSUE THREAD

**Issue by ambrons** [rxaviers/react-globalize-webpack-plugin#17]
I'm not entirely sure which project to put this on, but since I'm using react-globalize-webpack-plugin, react-globalize I figured this might be the best place to start.

I'm trying to use `<FormatCurrency/>` in our react components, but it's data driven.  So the code looks like so:

```
render() {
        const { rowIndex, field, data, ...props} = this.props;
        const { amount, currency } = tableDataLookup(data, rowIndex, field, Object);

        if (!amount) {
            console.error('no amount property in data on row %o.  Lookup: ', rowIndex, tableDataLookup);
        }

        return (
          <Cell {...props}>
            <AngledButton>
                <FormatCurrency currency={currency}>{amount}</FormatCurrency>
            </AngledButton>
          </Cell>
        );
    }
```

What happens during a production build however is I get the following message `currency is not defined`.  I've included the complete message below.  From looking around I've determined the issue is with my assumption of behavior and missunderstanding of what globalize-compiler is doing to build the formatters and parsers.

_my question is_ what's the expectation for dynamic data specifically `<FormatCurrency>`.

Thanks in advance.

_Full output of Webpack compile_

```
Populated the new fields of `messages/zh.json` using the default translation.
ReferenceError: currency is not defined
    at eval (eval at extractor (/Users/abrons/devel/zco/esports-ui/node_modules/react-globalize-compiler/lib/extract.js:65:10), <anonymous>:3:37)
    at /Users/abrons/devel/zco/esports-ui/node_modules/globalize-compiler/lib/compile-extracts.js:59:23
    at Array.reduce (native)
    at Object.compileExtracts (/Users/abrons/devel/zco/esports-ui/node_modules/globalize-compiler/lib/compile-extracts.js:58:49)
    at GlobalizeCompilerHelper.compile (/Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/GlobalizeCompilerHelper.js:63:33)
    at /Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:231:51
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:225:58
    at Array.forEach (native)
    at /Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:223:63
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:221:10)
    at Compilation.applyPlugins (/Users/abrons/devel/zco/esports-ui/node_modules/tapable/lib/Tapable.js:26:37)
    at Compilation.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Compilation.js:558:8)
    at Compilation.next (/Users/abrons/devel/zco/esports-ui/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:52:16
    at done (/Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:246:17)
    at /Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:44:16
    at /Users/abrons/devel/zco/esports-ui/node_modules/extract-text-webpack-plugin/index.js:269:6
    at /Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:52:16
    at done (/Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:246:17)
    at /Users/abrons/devel/zco/esports-ui/node_modules/async/lib/async.js:44:16
    at /Users/abrons/devel/zco/esports-ui/node_modules/extract-text-webpack-plugin/index.js:259:9
    at /Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Compilation.js:469:4
    at Array.forEach (native)
    at callback (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Compilation.js:468:14)
    at Compilation.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Compilation.js:489:4)
    at /Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Compilation.js:332:10
```

**Comment by ambrons** [comment]
Here's an example that demonstrates the issue:
https://github.com/ambrons/react-globalize-webpack-plugin/tree/example-for-17

**Comment by rxaviers** [comment]
Sorry for the insane long delay on replying you :grimacing: :blush: ...

This plugin parses your code statically and use globalize-compiler to generate the runtime bundle. It happens that all formatter options should be static, i.e., currency must be a static string, e.g., `'USD'`. I understand you may want to support several currencies. A way around this is to define one <FormatCurrency> for each currency and use the appropriate one. Another is to improve https://github.com/globalizejs/globalize-compiler with such support.

**Comment by rxaviers** [comment]
related https://github.com/rxaviers/globalize-webpack-plugin/issues/15

**Comment by rxaviers** [comment]
https://github.com/globalizejs/globalize-compiler/issues/10#issuecomment-173571256
